{% set data = load_setup_py_data() %}

package:
  name: reactiv
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 1

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - scikit-image
